version: '3.7'

services:
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    networks:
      - app-network

  mysql:
    image: "mysql:latest"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: stocks
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    #   interval: 5s
    #   timeout: 10s
    #   retries: 3

  # producer:
  #   build: ./producer
  #   environment:
  #     RABBITMQ_HOST: rabbitmq
  #     RABBITMQ_USER: user
  #     RABBITMQ_PASSWORD: password
  #   networks:
  #     - app-network
  #   depends_on:
  #     - rabbitmq

  # consumer:
  #   build: ./consumer
  #   environment:
  #     RABBITMQ_HOST: rabbitmq
  #     RABBITMQ_USER: user
  #     RABBITMQ_PASSWORD: password
  #     MYSQL_HOST: mysql
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: my-secret-pw
  #     MYSQL_DATABASE: mydatabase
  #   networks:
  #     - app-network
  #   depends_on:
  #     rabbitmq:
  #       condition: service_started
     

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
